server:
  port: 8666

spring-doc:
  swagger-ui:
    path: /swagger-ui.html

spring:
  application:
    name: greeting-service
  security:
    oauth2:
      resource-server:
        jwt:
          jwk-set-uri: http://www.oauth2.com:9000/oauth2/jwks

eureka:
  client:
    serviceUrl:
      defaultZone: http://www.eureka.com:8761/eureka/