server:
  port: 8666
  servlet:
    context-path: /greeting-service/

#spring-doc:
#  swagger-ui:
#    path: /swagger-ui.html

spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
  application:
    name: greeting-service
  datasource:
    url: jdbc:mysql://localhost/greeting
    username: root
    password: cy12345678
  security:
    oauth2:
      resource-server:
        jwt:
          jwk-set-uri: http://www.oauth2.com:9000/greeting-oauth2-service/oauth2/jwks

eureka:
  client:
    serviceUrl:
      defaultZone: http://www.eureka.com:8761/eureka/