server:
  port: 9000
  servlet:
    context-path: /greeting-oauth2-service

#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://www.eureka.com:8761/eureka/

spring:
  application:
    name: greeting-oauth2-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://www.eureka.com:8761/eureka/

logging:
  level:
    org.springframework.security: DEBUG
